import { DEFAULT_TIER_THRESHOLDS } from './product-pricing'
import type { Plant, Category, Order, PriceTier } from './types'

function makePriceTiers(basePrice: number): PriceTier[] {
  const discounts = [0.95, 0.9, 0.85, 0.8, 0.75, 0.7]
  return DEFAULT_TIER_THRESHOLDS.map((minQuantity, i) => ({
    minQuantity,
    pricePerUnit: Math.round(basePrice * discounts[i]),
  }))
}

export const categories: Category[] = [
  {
    id: '1',
    name: 'Хвойні',
    slug: 'conifers',
    description: 'Вічнозелені хвойні дерева та чагарники для вашого саду',
    image: '/images/conifer-category.jpg',
    plantCount: 45,
  },
  {
    id: '2',
    name: 'Листяні',
    slug: 'deciduous',
    description: 'Декоративні листяні дерева та чагарники',
    image: '/images/deciduous-category.jpg',
    plantCount: 38,
  },
  {
    id: '3',
    name: 'Багаторічники',
    slug: 'perennials',
    description: 'Квітучі багаторічні рослини для клумб та бордюрів',
    image: '/images/perennial-category.jpg',
    plantCount: 62,
  },
  {
    id: '4',
    name: 'Чагарники',
    slug: 'shrubs',
    description: 'Декоративні чагарники для живоплотів та композицій',
    image: '/images/plant-2.jpg',
    plantCount: 29,
  },
]

export const plants: Plant[] = [
  {
    id: '1',
    name: 'Туя західна Смарагд',
    latinName: 'Thuja occidentalis Smaragd',
    slug: 'thuja-occidentalis-smaragd',
    category: 'conifers',
    price: 450,
    originalPrice: 520,
    sku: 'TH-SM-C5-001',
    images: [
      '/images/plant-1.jpg',
      '/images/conifer-category.jpg',
      '/images/plant-3.jpg',
    ],
    description: 'Туя західна Смарагд - один з найпопулярніших сортів туї. Має вузьку конусоподібну форму крони та яскраво-зелене забарвлення хвої, яке зберігається протягом всього року. Ідеально підходить для створення живоплотів та солітерних посадок.',
    shortDescription: 'Вузька конусоподібна туя з яскраво-зеленою хвоєю',
    stock: 125,
    containerSize: 'C5',
    height: '80-100 см',
    sunRequirement: 'full-sun',
    soilType: 'any',
    hardinessZone: '3-8',
    wateringNeeds: 'moderate',
    plantingInstructions: 'Висаджувати на сонячному місці у добре дреновану почву. Відстань між рослинами для живоплоту - 50-60 см.',
    lightRequirements: 'Сонячне місце, допускається легка напівтінь. У тіні крона стає рихлою.',
    careInstructions: 'Регулярний полив у перший рік після посадки. Підживлення спеціальним добривом для хвойних навесні.',
    isNew: true,
    isFeatured: true,
    createdAt: '2024-01-15',
    variants: [
      {
        id: '1-c2',
        label: 'C2',
        stock: 420,
        basePrice: 320,
        priceTiers: makePriceTiers(320),
      },
      {
        id: '1-c5',
        label: 'C5',
        stock: 125,
        basePrice: 450,
        priceTiers: makePriceTiers(450),
      },
      {
        id: '1-c7',
        label: 'C7',
        stock: 68,
        basePrice: 620,
        priceTiers: makePriceTiers(620),
      },
      {
        id: '1-cvr',
        label: 'СВРБ, ТГ22-24, Н300-400, РА180-200',
        stock: 0,
        availableFrom: '25.05.2026',
        basePrice: 780,
        priceTiers: makePriceTiers(780),
      },
    ],
  },
  {
    id: '2',
    name: 'Ялина блакитна Глаука',
    latinName: 'Picea pungens Glauca',
    slug: 'picea-pungens-glauca',
    category: 'conifers',
    price: 890,
    sku: 'SP-GL-C7-001',
    images: [
      '/images/conifer-category.jpg',
      '/images/plant-1.jpg',
      '/images/plant-3.jpg',
    ],
    description: 'Ялина блакитна Глаука - величний хвойник із срібласто-блакитною хвоєю. Рослина має правильну конічну форму та повільний ріст. Чудово виглядає як солітер на газоні.',
    shortDescription: 'Величний хвойник зі срібласто-блакитною хвоєю',
    stock: 45,
    containerSize: 'C7',
    height: '100-120 см',
    sunRequirement: 'full-sun',
    soilType: 'neutral',
    hardinessZone: '2-7',
    wateringNeeds: 'moderate',
    plantingInstructions: 'Потребує сонячного місця та добре дренованого ґрунту. Не переносить застою води.',
    lightRequirements: 'Повне сонце забезпечує найкраще забарвлення хвої.',
    careInstructions: 'Помірний полив, мульчування прикореневої зони. Обрізка зазвичай не потрібна.',
    isFeatured: true,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    name: 'Клен гостролистий Друммонда',
    latinName: 'Acer platanoides Drummondii',
    slug: 'acer-platanoides-drummondii',
    category: 'deciduous',
    price: 1250,
    sku: 'AC-DR-C10-001',
    images: [
      '/images/deciduous-category.jpg',
      '/images/plant-2.jpg',
    ],
    description: 'Клен гостролистий Друммонда - декоративне листяне дерево з ефектним строкатим листям. Листки мають широку білу облямівку, що надає дереву святкового вигляду протягом всього сезону.',
    shortDescription: 'Декоративний клен з білоокаймленим листям',
    stock: 18,
    containerSize: 'C10',
    height: '150-180 см',
    sunRequirement: 'partial-shade',
    soilType: 'neutral',
    hardinessZone: '4-7',
    wateringNeeds: 'moderate',
    plantingInstructions: 'Оптимальне місце - легка напівтінь. Захистити від спекотного полуденного сонця.',
    lightRequirements: 'Напівтінь або розсіяне світло. На яскравому сонці листя може підгорати.',
    careInstructions: 'Регулярний полив у спеку. Формуюча обрізка рано навесні до початку сокоруху.',
    isNew: true,
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Гортензія волотиста Лаймлайт',
    latinName: 'Hydrangea paniculata Limelight',
    slug: 'hydrangea-paniculata-limelight',
    category: 'shrubs',
    price: 380,
    originalPrice: 420,
    sku: 'HY-LL-C3-001',
    images: [
      '/images/plant-2.jpg',
      '/images/perennial-category.jpg',
    ],
    description: 'Гортензія волотиста Лаймлайт - один з найкращих сортів волотистих гортензій. Великі конусоподібні суцвіття спочатку мають лаймово-зелений колір, згодом біліють, а восени набувають рожевого відтінку.',
    shortDescription: 'Розкішна гортензія з лаймово-білими суцвіттями',
    stock: 67,
    containerSize: 'C3',
    height: '40-60 см',
    sunRequirement: 'partial-shade',
    soilType: 'acidic',
    hardinessZone: '3-8',
    wateringNeeds: 'high',
    plantingInstructions: 'Садити у вологу, багату на гумус кислу почву. Ідеальне місце - ранкове сонце та післяобідня тінь.',
    lightRequirements: 'Напівтінь або вранішнє сонце. Уникати спекотного полуденного сонця.',
    careInstructions: 'Рясний полив, особливо у спеку. Обрізка рано навесні на 2-3 бруньки.',
    isFeatured: true,
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    name: 'Хоста Халціон',
    latinName: 'Hosta Halcyon',
    slug: 'hosta-halcyon',
    category: 'perennials',
    price: 180,
    sku: 'HO-HA-P9-001',
    images: [
      '/images/perennial-category.jpg',
      '/images/plant-2.jpg',
    ],
    description: 'Хоста Халціон - один з найкращих блакитнолистих сортів хости. Має щільне серцеподібне листя інтенсивного блакитного кольору з восковим нальотом. Чудово виглядає у тінистих куточках саду.',
    shortDescription: 'Блакитнолиста хоста для тінистих куточків',
    stock: 89,
    containerSize: 'P9',
    height: '15-20 см',
    sunRequirement: 'full-shade',
    soilType: 'neutral',
    hardinessZone: '3-9',
    wateringNeeds: 'moderate',
    plantingInstructions: 'Висаджувати у тіні або напівтіні у вологий, багатий на органіку ґрунт.',
    lightRequirements: 'Тінь або напівтінь. Пряме сонце викликає опіки на листі.',
    careInstructions: 'Регулярний полив, мульчування. Захист від слимаків.',
    createdAt: '2024-01-25',
  },
  {
    id: '6',
    name: 'Ялівець лускатий Блю Карпет',
    latinName: 'Juniperus squamata Blue Carpet',
    slug: 'juniperus-squamata-blue-carpet',
    category: 'conifers',
    price: 320,
    sku: 'JN-BC-C2-001',
    images: [
      '/images/plant-1.jpg',
    ],
    description: 'Ялівець лускатий Блю Карпет - ґрунтопокривний хвойник з розпростертою формою крони та срібласто-блакитною хвоєю. Ідеальний для альпійських гірок, схилів та переднього плану композицій.',
    shortDescription: 'Ґрунтопокривний ялівець з блакитною хвоєю',
    stock: 156,
    containerSize: 'C2',
    height: '15-20 см',
    sunRequirement: 'full-sun',
    soilType: 'any',
    hardinessZone: '4-8',
    wateringNeeds: 'low',
    plantingInstructions: 'Сонячне місце, добре дренований ґрунт. Не переносить застою води.',
    lightRequirements: 'Повне сонце для найкращого забарвлення.',
    careInstructions: 'Невибагливий. Полив тільки у посушливий період.',
    isNew: true,
    createdAt: '2024-02-05',
  },
  {
    id: '7',
    name: 'Бузок звичайний Сенсація',
    latinName: 'Syringa vulgaris Sensation',
    slug: 'syringa-vulgaris-sensation',
    category: 'shrubs',
    price: 450,
    sku: 'SY-SN-C5-001',
    images: [
      '/images/plant-2.jpg',
    ],
    description: 'Бузок звичайний Сенсація - унікальний сорт з двоколірними квітками. Пурпурово-червоні пелюстки мають білу облямівку, що створює ефектний контраст. Інтенсивний солодкий аромат.',
    shortDescription: 'Ефектний бузок з двоколірними квітками',
    stock: 34,
    containerSize: 'C5',
    height: '60-80 см',
    sunRequirement: 'full-sun',
    soilType: 'neutral',
    hardinessZone: '3-7',
    wateringNeeds: 'moderate',
    plantingInstructions: 'Сонячне місце, родючий добре дренований ґрунт. Уникати низьких вологих місць.',
    lightRequirements: 'Повне сонце забезпечує рясне цвітіння.',
    careInstructions: 'Обрізка відцвілих суцвіть. Омолоджуюча обрізка старих кущів.',
    isFeatured: true,
    createdAt: '2024-01-18',
  },
  {
    id: '8',
    name: 'Ехінацея пурпурова Магнус',
    latinName: 'Echinacea purpurea Magnus',
    slug: 'echinacea-purpurea-magnus',
    category: 'perennials',
    price: 145,
    sku: 'EC-MG-P9-001',
    images: [
      '/images/perennial-category.jpg',
    ],
    description: 'Ехінацея пурпурова Магнус - великоквіткова ехінацея з рожево-пурпуровими пелюстками та помаранчевим центром. Цвіте з липня по вересень, приваблює метеликів та бджіл.',
    shortDescription: 'Яскрава ехінацея для сонячних клумб',
    stock: 112,
    containerSize: 'P9',
    height: '10-15 см',
    sunRequirement: 'full-sun',
    soilType: 'neutral',
    hardinessZone: '3-9',
    wateringNeeds: 'low',
    plantingInstructions: 'Сонячне місце, добре дренований ґрунт. Витримує посуху.',
    lightRequirements: 'Повне сонце для кращого цвітіння.',
    careInstructions: 'Видалення відцвілих суцвіть продовжує цвітіння. Ділення кожні 3-4 роки.',
    createdAt: '2024-01-22',
  },
]

export const orders: Order[] = [
  {
    id: '1',
    orderNumber: 'ZY-2024-001',
    customerName: 'Олена Коваленко',
    customerEmail: 'olena.kovalenko@email.com',
    customerPhone: '+380 67 123 4567',
    shippingAddress: 'м. Київ, вул. Хрещати��, 22, кв. 15',
    items: [
      { plant: plants[0], quantity: 10 },
      { plant: plants[3], quantity: 5 },
    ],
    total: 6400,
    status: 'processing',
    createdAt: '2024-02-10T10:30:00Z',
    updatedAt: '2024-02-10T14:00:00Z',
  },
  {
    id: '2',
    orderNumber: 'ZY-2024-002',
    customerName: 'Петро Шевченко',
    customerEmail: 'petro.shevchenko@email.com',
    customerPhone: '+380 50 987 6543',
    shippingAddress: 'м. Львів, вул. Франка, 45',
    items: [
      { plant: plants[1], quantity: 2 },
      { plant: plants[6], quantity: 3 },
    ],
    total: 3130,
    status: 'shipped',
    createdAt: '2024-02-09T15:45:00Z',
    updatedAt: '2024-02-11T09:00:00Z',
  },
  {
    id: '3',
    orderNumber: 'ZY-2024-003',
    customerName: 'Марія Бондаренко',
    customerEmail: 'maria.bondarenko@email.com',
    customerPhone: '+380 63 456 7890',
    shippingAddress: 'м. Одеса, вул. Дерибасівська, 10',
    items: [
      { plant: plants[2], quantity: 1 },
      { plant: plants[4], quantity: 8 },
    ],
    total: 2690,
    status: 'pending',
    createdAt: '2024-02-11T08:20:00Z',
    updatedAt: '2024-02-11T08:20:00Z',
  },
]

export const containerSizes = [
  { value: 'P9', label: 'P9 (Ø 9 см)' },
  { value: 'C2', label: 'C2 (2 л)' },
  { value: 'C3', label: 'C3 (3 л)' },
  { value: 'C5', label: 'C5 (5 л)' },
  { value: 'C7', label: 'C7 (7 л)' },
  { value: 'C10', label: 'C10 (10 л)' },
  { value: 'C20', label: 'C20 (20 л)' },
  { value: 'C30', label: 'C30 (30 л)' },
]

export const sunRequirements = [
  { value: 'full-sun', label: 'Повне сонце' },
  { value: 'partial-shade', label: 'Напівтінь' },
  { value: 'full-shade', label: 'Тінь' },
]

export const soilTypes = [
  { value: 'acidic', label: 'Кислий' },
  { value: 'neutral', label: 'Нейтральний' },
  { value: 'alkaline', label: 'Лужний' },
  { value: 'any', label: 'Будь-який' },
]

export const hardinessZones = [
  { value: '2-7', label: 'Зона 2-7' },
  { value: '3-7', label: 'Зона 3-7' },
  { value: '3-8', label: 'Зона 3-8' },
  { value: '3-9', label: 'Зона 3-9' },
  { value: '4-7', label: 'Зона 4-7' },
  { value: '4-8', label: 'Зона 4-8' },
]
